export const COMMENTS = [
  {
    id: 0,
    cosmoId: 0,
    rating: 5,
    text: "What a magnificent view!",
    author: "Tinus Lorvaldes",
    date: "2018-10-25T16:30Z",
  },
  {
    id: 1,
    cosmoId: 0,
    rating: 4,
    text: "The nebula is beautiful!",
    author: "Brennen Ech",
    date: "2017-06-17T03:33Z",
  },
  {
    id: 2,
    cosmoId: 0,
    rating: 5,
    text: "I caught a world-record-breaking sunburn here on my last visit.",
    author: "McKenzie Sebastian",
    date: "2019-02-18T18:12Z",
  },
  {
    id: 3,
    cosmoId: 0,
    rating: 5,
    text: "Amazing!!",
    author: "Jordan Runn",
    date: "2019-08-04T20:11Z",
  },
  {
    id: 4,
    cosmoId: 0,
    rating: 4,
    text: "The stars at night were a revelation!",
    author: "Ann Dabramov",
    date: "2018-07-23T19:44Z",
  },
  {
    id: 5,
    cosmoId: 1,
    rating: 4,
    text: "The image is beautiful!",
    author: "Brennen Ech",
    date: "2017-06-17T03:33Z",
  },
  {
    id: 6,
    cosmoId: 1,
    rating: 5,
    text: "I caught a world-record-breaking sunburn here on my last visit.",
    author: "McKenzie Sebastian",
    date: "2019-02-18T18:12Z",
  },
  {
    id: 7,
    cosmoId: 1,
    rating: 5,
    text: "Amazing!!.",
    author: "Jordan Runn",
    date: "2019-08-04T20:11Z",
  },
  {
    id: 8,
    cosmoId: 1,
    rating: 4,
    text: "The stars at night were a revelation!",
    author: "Ann Dabramov",
    date: "2018-07-23T19:44Z",
  },
  {
    id: 9,
    cosmoId: 1,
    rating: 5,
    text: "What a magnificent view!",
    author: "Tinus Lorvaldes",
    date: "2018-10-25T16:30Z",
  },
  {
    id: 10,
    cosmoId: 2,
    rating: 5,
    text: "I caught a world-record-breaking sunburn here on my last visit.",
    author: "McKenzie Sebastian",
    date: "2019-02-18T18:12Z",
  },
  {
    id: 11,
    cosmoId: 2,
    rating: 5,
    text: "Amazing!!.",
    author: "Jordan Runn",
    date: "2019-08-04T20:11Z",
  },
  {
    id: 12,
    cosmoId: 2,
    rating: 4,
    text: "The stars at night were a revelation!",
    author: "Ann Dabramov",
    date: "2018-07-23T19:44Z",
  },
  {
    id: 13,
    cosmoId: 2,
    rating: 5,
    text: "What a magnificent view!",
    author: "Tinus Lorvaldes",
    date: "2018-10-25T16:30Z",
  },
  {
    id: 14,
    cosmoId: 2,
    rating: 4,
    text: "Moons over my hammy!",
    author: "Brennen Ech",
    date: "2017-06-17T03:33Z",
  },
  {
    id: 15,
    cosmoId: 3,
    rating: 5,
    text: "Amazing!!.",
    author: "Jordan Runn",
    date: "2019-08-04T20:11Z",
  },
  {
    id: 16,
    cosmoId: 3,
    rating: 4,
    text: "The stars at night were a revelation!",
    author: "Ann Dabramov",
    date: "2018-07-23T19:44Z",
  },
  {
    id: 17,
    cosmoId: 3,
    rating: 5,
    text: "What a magnificent view!",
    author: "Tinus Lorvaldes",
    date: "2018-10-25T16:30Z",
  },
  {
    id: 18,
    cosmoId: 3,
    rating: 4,
    text: "The photo is amazing!",
    author: "Brennen Ech",
    date: "2017-06-17T03:33Z",
  },
  {
    id: 19,
    cosmoId: 3,
    rating: 5,
    text: "I caught a world-record-breaking sunburn here on my last visit.",
    author: "McKenzie Sebastian",
    date: "2019-02-18T18:12Z",
  },
  {
    id: 20,
    cosmoId: 4,
    rating: 4,
    text: "The stars at night were a revelation!",
    author: "Ann Dabramov",
    date: "2018-07-23T19:44Z",
  },
  {
    id: 21,
    cosmoId: 4,
    rating: 5,
    text: "What a magnificent view!",
    author: "Tinus Lorvaldes",
    date: "2018-10-25T16:30Z",
  },
  {
    id: 22,
    cosmoId: 4,
    rating: 4,
    text: "The photo is amazing!",
    author: "Brennen Ech",
    date: "2017-06-17T03:33Z",
  },
  {
    id: 23,
    cosmoId: 5,
    rating: 5,
    text: "I caught a world-record-breaking sunburn here on my last visit.",
    author: "McKenzie Sebastian",
    date: "2019-02-18T18:12Z",
  },
  {
    id: 24,
    cosmoId: 5,
    rating: 5,
    text: "Amazing!!.",
    author: "Jordan Runn",
    date: "2019-08-04T20:11Z",
  },
  {
    id: 25,
    cosmoId: 5,
    rating: 4,
    text: "The stars at night were a revelation!",
    author: "Ann Dabramov",
    date: "2018-07-23T19:44Z",
  },
  {
    id: 26,
    cosmoId: 5,
    rating: 5,
    text: "What a magnificent view!",
    author: "Tinus Lorvaldes",
    date: "2018-10-25T16:30Z",
  },
  {
    id: 27,
    cosmoId: 5,
    rating: 4,
    text: "The photo is amazing!",
    author: "Brennen Ech",
    date: "2017-06-17T03:33Z",
  },
  {
    id: 28,
    cosmoId: 5,
    rating: 5,
    text: "I caught a world-record-breaking sunburn here on my last visit.",
    author: "McKenzie Sebastian",
    date: "2019-02-18T18:12Z",
  },
];
