export const COSMOS = [
  {
    id: 0,
    title: "Cosmos",
    subtitle: "Stars, Galaxies and Nebulae",
    type: {
      star: true,
      solarsystem: false,
      spacetech: false,
    },
    name: "In the Heart of the Heart Nebula",
    image: "/assets/images/HeartB_Jensen_3925-600h.jpg",
    credit: "Adam Jensen",
    date: "2022 February 14",
    featured: true,
    explanation:
      "What excites the Heart Nebula? First, the large emission nebula dubbed IC 1805 looks, in whole, like a human heart. Its shape perhaps fitting of the Valentine's Day, this heart glows brightly in red light emitted by its most prominent element: excited hydrogen. The red glow and the larger shape are all created by a small group of stars near the nebula's center. In the heart of the Heart Nebula are young stars from the open star cluster Melotte 15 that are eroding away several picturesque dust pillars with their energetic light and winds. The open cluster of stars contains a few bright stars nearly 50 times the mass of our Sun, many dim stars only a fraction of the mass of our Sun, and an absent microquasar that was expelled millions of years ago. The Heart Nebula is located about 7,500 light years away toward the constellation of the mythological Queen of Aethiopia (Cassiopeia).",
  },
  {
    id: 1,
    title: "Cosmos",
    subtitle: "Stars, Galaxies and Nebulae",
    type: {
      star: true,
      solarsystem: false,
      spacetech: false,
    },
    name: "Chamaeleon I Molecular Cloud",
    image: "/assets/images/Chamaeleon_RobertEder-600h.jpg",
    credit:
      "Acquisition: Stas Volskiy (Chilescope.com), Processing: Robert Eder",
    date: "2022 February 17",
    featured: false,
    explanation:
      "Dark markings and bright nebulae in this telescopic southern sky view are telltale signs of young stars and active star formation. They lie a mere 650 light-years away, at the boundary of the local bubble and the Chamaeleon molecular cloud complex. Regions with young stars identified as dusty reflection nebulae from the 1946 Cederblad catalog include the C-shaped Ced 110 just above and left of center, and bluish Ced 111 below it. Also a standout in the frame, the orange tinted V-shape of the Chamaeleon Infrared Nebula (Cha IRN) was carved by material streaming from a newly formed low-mass star. The well-composed image spans 1.5 degrees. That's about 17 light-years at the estimated distance of the nearby Chamaeleon I molecular cloud.",
  },
  {
    id: 2,
    title: "Solar System",
    subtitle: "Stars, Galaxies and Nebulae",
    type: {
      star: true,
      solarsystem: false,
      spacetech: false,
    },
    name: "IC 1396 H-Alpha Close-Up",
    image: "/assets/images/ic1396b_wright_f50-600h.jpg",
    credit: "Nick Wright (University College London), IPHAS Collaboration",
    date: "2005 September 30",
    featured: false,
    explanation:
      "Clouds of glowing hydrogen gas mingle ominously with dark dust lanes in this close-up of IC 1396, an active star forming region some 2,000 light years away in the constellation Cepheus. In this and other similar emission nebulae, energetic ultraviolet light from a hot young star strips electrons from the surrounding hydrogen atoms. As the electrons and atoms recombine they emit longer wavelength, lower energy light in a well known characteristic pattern of bright spectral lines. At visible wavelengths, the strongest emission line in this pattern is in the red part of the spectrum and is known as Hydrogen-alpha or just H-alpha. Part of IPHAS, a survey of H-alpha emission in our Milky Way Galaxy, this image spans about 20 light-years and highlights bright, dense regions within IC 1396, likely sites where massive new stars are born.",
  },
  {
    id: 3,
    title: "Cosmos",
    subtitle: "Stars, Galaxies and Nebulae",
    type: {
      star: true,
      solarsystem: false,
      spacetech: false,
    },
    name: "Three Clusters Puppis in Puppis",
    image: "/assets/images/ThreeClustersPuppis-600h.jpg",
    credit: "Dave Doctor",
    date: "2022 February 18",
    featured: false,
    explanation:
      "Galactic or open star clusters are young. The swarms of stars are born together near the plane of the Milky Way, but their numbers steadily dwindle as cluster members are ejected by galactic tides and gravitational interactions. Caught in this telescopic frame over three degrees across are three good examples of galactic star clusters, seen toward the southern sky's nautical constellation Puppis. Below and left, M46 is some 5,500 light-years in the distance. Right of center M47 is only 1,600 light-years away and NGC 2423 (top) is about 2500 light-years distant. Around 300 million years young M46 contains a few hundred stars in a region about 30 light-years across. Sharp eyes can spot a planetary nebula, NGC 2438, at about 11 o'clock against the M46 cluster stars. But that nebula's central star is billions of years old, and NGC 2438 is likely a foreground object only by chance along the line of sight to youthful M46. Even younger, aged around 80 million years, M47 is a smaller and looser star cluster spanning about 10 light-years. Star cluster NGC 2423 is pushing about 750 million years in age though. NGC 2423 is known to harbor an extrasolar planet, detected orbiting one of its red giant stars.",
  },
  {
    id: 4,
    title: "Cosmos",
    subtitle: "Stars, Galaxies and Nebulae",
    type: {
      star: true,
      solarsystem: false,
      spacetech: false,
    },
    name: "Dueling Bands in the Night",
    image: "/assets/images/DuelingBands_Dai_2000-600h.jpg",
    credit: "Jeff Dai (TWAN)",
    date: "2022 March 1",
    featured: false,
    explanation:
      "What are these two bands in the sky? The more commonly seen band is the one on the right and is the central band of our Milky Way galaxy. Our Sun orbits in the disk of this spiral galaxy, so that from inside, this disk appears as a band of comparable brightness all the way around the sky. The Milky Way band can also be seen all year -- if out away from city lights. The less commonly seem band, on the left, is zodiacal light -- sunlight reflected from dust orbiting the Sun in our Solar System. Zodiacal light is brightest near the Sun and so is best seen just before sunrise or just after sunset. On some evenings in the north, particularly during the months of March and April, this ribbon of zodiacal light can appear quite prominent after sunset. It was determined only this century that zodiacal dust was mostly expelled by comets that have passed near Jupiter. Only on certain times of the year will the two bands be seen side by side, in parts of the sky, like this. The featured image, including the Andromeda galaxy and a meteor, was captured in late January over a frozen lake in Kanding, Sichuan, China.",
  },
  {
    id: 5,
    title: "Cosmos",
    subtitle: "Stars, Galaxies and Nebulae",
    type: {
      star: true,
      solarsystem: false,
      spacetech: false,
    },
    name: "Star Formation in the Eagle Nebula",
    image: "/assets/images/Pillars_HstBibillo_1097-600h.jpg",
    credit:
      "NASA, ESA, Hubble; Processing & Copyright: Ignacio Diaz Bobillo & Diego Gravinese",
    date: "2022 March 14",
    featured: false,
    explanation:
      "Where do stars form? One place, star forming regions known as 'EGGs', are being uncovered at the end of this giant pillar of gas and dust in the Eagle Nebula (M16). Short for evaporating gaseous globules, EGGs are dense regions of mostly molecular hydrogen gas that fragment and gravitationally collapse to form stars. Light from the hottest and brightest of these new stars heats the end of the pillar and causes further evaporation of gas and dust -- revealing yet more EGGs and more young stars. This featured picture was created from exposures spanning over 30 hours with the Earth-orbiting Hubble Space Telescope in 2014, and digitally processed with modern software by experienced volunteers in Argentina. Newborn stars will gradually destroy their birth pillars over the next 100,000 years or so -- if a supernova doesn't destroy them first.",
  },
  {
    id: 6,
    name: "A Year of Assessing Astronomical Hazards",
    title: "Solar System",
    subtitle: "Asteroids, Comets and Planets",
    type: {
      star: false,
      solarsystem: true,
      spacetech: false,
    },
    image: "/assets/images/caldera_durda_big-600h.jpg",
    credit: "Dan Dura (SWRI)",
    date: "2002 December 31",
    featured: false,
    explanation:
      "Could an asteroid destroy civilization on Earth? Mountain-sized space rocks could potentially impact the Earth causing global effects, and perhaps even be mistaken for a nuclear blast of terrestrial origin. Such large impacts are rare but have happened before. Modern telescopes have therefore begun to scan the skies for signs of approaching celestial hazards. Over the past year, projects such as Spacewatch and Spaceguard have continually discovered previously unknown asteroids that indeed pass near the Earth. Such projects are still rather modest, however. In June, 100-meter asteroid 2002 MN was discovered only after it whizzed by the Earth, crossing even within the orbit of the Moon. This year brought much discussion in the astronomical community of expanding technology to discover most large Near Earth Objects and extend the time between discovery and impact for all potential astronomical hazards. Pictured above is an illustration of a busy planetary system, showing the view of a planet ringed with space debris from a recently formed crater of an orbiting moon.",
  },
  {
    id: 7,
    name: "Ida and Dactyl: Asteroid and Moon",
    title: "Solar System",
    subtitle: "Asteroids, Comets and Planets",
    type: {
      star: false,
      solarsystem: true,
      spacetech: false,
    },
    image: "/assets/images/idadactyl_galileo_big-600h.jpg",
    credit: "Galileo Project, JPL, NASA",
    date: "2004 June 19",
    featured: false,
    explanation:
      "This asteroid has a moon! The robot spacecraft Galileo destined to explore the Jovian system, encountered and photographed two asteroids during its long interplanetary voyage to Jupiter. The second asteroid it photographed, Ida, was discovered to have a moon which appears as a small dot to the right of Ida in this image from 1993. The tiny moon, named Dactyl, is about one mile across, while the potato shaped Ida measures about 36 miles long and 14 miles wide. Dactyl is the first moon of an asteroid ever discovered. The names Ida and Dactyl are from Greek mythology. Many other asteroids are now known to have moons.",
  },
  {
    id: 8,
    name: "Asteroids in the Distance",
    title: "Solar System",
    subtitle: "Asteroids, Comets and Planets",
    type: {
      star: false,
      solarsystem: true,
      spacetech: false,
    },
    image: "/assets/images/asteroids_hst_big-600h.jpg",
    credit: "R. Evans & K. Stapelfeldt (JPL), WFPC2, HST, NASA",
    date: "2005 April 17",
    featured: false,
    explanation:
      "Rocks from space hit Earth every day. The larger the rock, though, the less often Earth is struck. Many kilograms of space dust pitter to Earth daily. Larger bits appear initially as a bright meteor. Baseball-sized rocks and ice-balls streak through our atmosphere daily, most evaporating quickly to nothing. Significant threats do exist for rocks near 100 meters in diameter, which strike the Earth roughly every 1000 years. An object this size could cause significant tsunamis were it to strike an ocean, potentially devastating even distant shores. A collision with a Massive asteroid, over 1 km across, is more rare, occurring typically millions of years apart, but could have truly global consequences. Many asteroids remain undiscovered. In fact, one was discovered in 1998 as the long blue streak in the above archival image taken by the Hubble Space Telescope. In 2002 June, the small 100-meter asteroid 2002 MN was discovered only after it whizzed by the Earth, passing well within the orbit of the Moon. 2002 MN passed closer than any asteroid since 1994 XM1, but not as close as 2004 MN4 will pass in 2029. A collision with a large asteroid would not affect Earth's orbit so much as raise dust that would affect Earth's climate. One likely result is a global extinction of many species of life, possibly dwarfing the ongoing extinction occurring now.",
  },
  {
    id: 9,
    name: "Comet Hale-Bopp Over Val Parola Pass",
    title: "Solar System",
    subtitle: "Asteroids, Comets and Planets",
    type: {
      star: false,
      solarsystem: true,
      spacetech: false,
    },
    image: "/assets/images/halebopp5_aac_big-600h.jpg",
    credit: "A. Dimai, (Col Druscie Obs.), AAC",
    date: "2005 September 4",
    featured: false,
    explanation:
      "Comet Hale-Bopp became much brighter than any surrounding stars. It was seen even over bright city lights. Out away from city lights, however, it put on quite a spectacular show. Here Comet Hale-Bopp was photographed above Val Parola Pass in the Dolomite mountains surrounding Cortina d'Ampezzo, Italy. Comet Hale-Bopp's blue ion tail was created when fast moving particles from the solar wind struck expelled ions from the comet's nucleus. The white dust tail is composed of larger particles of dust and ice expelled by the nucleus that orbit behind the comet. Observations showed that Comet Hale-Bopp's nucleus spins about once every 12 hours.",
  },
  {
    id: 10,
    name: "The Dust and Ion Tails of Comet Hale-Bopp",
    title: "Solar System",
    subtitle: "Asteroids, Comets and Planets",
    type: {
      star: false,
      solarsystem: true,
      spacetech: false,
    },
    image: "/assets/images/halebopp_gleason_big-600h.jpg",
    credit: " John Gleason (Celestial Images)",
    date: "2005 May 22",
    featured: true,
    explanation:
      "In 1997, Comet Hale-Bopp's intrinsic brightness exceeded any comet since 1811. Since it peaked on the other side of the Earth's orbit, however, the comet appeared only brighter than any comet in two decades. Visible above are the two tails shed by Comet Hale-Bopp. The blue ion tail is composed of ionized gas molecules, of which carbon monoxide particularly glows blue when reacquiring electrons. This tail is created by the particles from the fast solar wind interacting with gas from the comet's head. The blue ion tail points directly away from the Sun. The light colored dust tail is created by bits of grit that have come off the comet's nucleus and are being pushed away by the pressure of light from the Sun. This tail points nearly away from the Sun. The above photograph was taken in March 1997.",
  },
  {
    id: 11,
    name: "Comet Hale-Bopp and the North America Nebula",
    title: "Solar System",
    subtitle: "Asteroids, Comets and Planets",
    type: {
      star: false,
      solarsystem: true,
      spacetech: false,
    },
    image: "/assets/images/hbnortham_jc_big-600h.jpg",
    credit: "Juan Carlos Casado",
    date: "2004 October 3",
    featured: false,
    explanation:
      "Comet Hale-Bopp's 1997 encounter with the inner Solar System allowed many breath-taking pictures. Above, Comet Hale-Bopp was photographed crossing the constellation of Cygnus, sporting spectacular yellow dust and blue ion tails. Visible on the right in red is the North America Nebula, a bright emission nebula observable from a dark location with binoculars. The North America Nebula is about 1500 light-years away, much farther than the comet, which was only about 8 light minutes away. Several bright blue stars from the open cluster M39 are visible just above the comet's blue ion tail.",
  },
  {
    id: 12,
    name: "Oceans Under Jupiter's Callisto?",
    title: "Solar System",
    subtitle: "Asteroids, Comets and Planets",
    type: {
      star: false,
      solarsystem: true,
      spacetech: false,
    },
    image: "/assets/images/callistocrescent_vg1_big-600h.jpg",
    credit: "Voyager 1, NASA",
    date: "2001 July 31",
    featured: false,
    explanation:
      "Why does Jupiter's moon Callisto alter the magnetic field of Jupiter in its vicinity? Callisto itself does not have a strong magnetic field. One possible answer is that Callisto harbors sub-surface oceans of electrically conducting salt-water. This hypothesis was bolstered recently by a new analysis of how Callisto creates and dissipates heat. Callisto is thought to create heat by the radioactive decay of internal rock -- a process that keeps the Earth's mantle molten. Callisto may not be able to dissipate this heat very efficiently, however, as it has thick layers of ice and rock on its surface. Perhaps this heat is enough to keep sub-surface water from freezing into ice. With this hypothesis, Callisto joins two other of Jupiter's moons, Europa and Ganymede, in candidates for sub-surface oceans. Callisto's oceans, however, might prove too hostile to support Earth-like life.",
  },
  {
    id: 13,
    name: "Europa Rotating",
    title: "Solar System",
    subtitle: "Asteroids, Comets and Planets",
    type: {
      star: false,
      solarsystem: true,
      spacetech: false,
    },
    image: "/assets/images/europarotmovie_gal-600h.gif",
    credit: "Calvin J. Hamilton, Voyager Team, NASA",
    date: "2001 January 16",
    featured: false,
    explanation:
      "Evidence has been mounting that beneath the vast planes of ice that cover Europa lies water -- liquid oceans that might be home to alien life. The smallest of Jupiter's Galilean Moons (which include Io, Ganymede, and Callisto), Europa's deep interior is composed of mostly of silicate rock. Upon close inspection, many surface cracks stop abruptly only to continue on somewhere else -- indicating surface plates that might be sliding. The above time-lapse sequence is a composite of images taken during the Voyager spacecraft flyby of the moon twenty years ago. Not all regions are resolved in high detail. The movie shows Europa during a complete rotation, which corresponds to a complete revolution around Jupiter since Europa always keeps the same face toward the giant planet. The cause of many of the surface colors on Europa also remains a topic of research.",
  },
  {
    id: 14,
    name: "Ganymede Mosaic",
    title: "Solar System",
    subtitle: "Asteroids, Comets and Planets",
    type: {
      star: false,
      solarsystem: true,
      spacetech: false,
    },
    image: "/assets/images/ganymede_galmosaic_big-600h.jpg",
    credit: "Galileo Project, DLR, JPL, NASA",
    date: "March 4, 1999",
    featured: false,
    explanation:
      "Ganymede, one of the four Galilean moons of Jupiter, is the largest moon in the Solar System. With a diameter of 5,260 kilometers it is even larger than planets Mercury and Pluto and just over three quarters the size of Mars. Ganymede is locked in synchronous rotation with Jupiter. This detailed mosaic of images from the Galileo spacecraft shows the trailing hemisphere of this planet-sized moon. Speckled with bright young craters, Ganymede's surface shows a mixture of old, dark, cratered terrain and lighter regions laced with grooves and ridges. Ganymede's true colors tend toward subtle browns and grays, but this mosaic's colors have been enhanced to increase surface contrasts. The violet shades extending from the top and bottom are likely due to frost particles in Ganymede's polar regions.",
  },
  {
    id: 15,
    name: "Atlantis to Orbit",
    title: "Space Tech",
    subtitle: "Rockets and Observatories",
    type: {
      star: false,
      solarsystem: false,
      spacetech: true,
    },
    image: "/assets/images/nightlaunch_sts104_big-600h.jpg",
    credit: "NASA",
    date: "2004 December 12",
    featured: false,
    explanation:
      "Birds don't fly this high. Airplanes don't go this fast. The Statue of Liberty weighs less. No species other than human can even comprehend what is going on, nor could any human just a millennium ago. The launch of a rocket bound for space is an event that inspires awe and challenges description. Pictured above, the Space Shuttle Atlantis lifted off to visit the International Space Station during the early morning hours of 2001 July 12. From a standing start, the two million kilogram rocket ship left to circle the Earth where the outside air is too thin to breathe and where there is little noticeable onboard gravity. Rockets bound for space are now launched from somewhere on Earth about once a week.",
  },
  {
    id: 16,
    name: "Saturn The Giant",
    title: "Space Tech",
    subtitle: "Rockets and Observatories",
    type: {
      star: false,
      solarsystem: false,
      spacetech: true,
    },
    image: "/assets/images/as13_nasa_big-600h.jpg",
    credit: "NASA",
    date: "2004 December 12",
    featured: false,
    explanation:
      "Forty years ago today (May 25, 1961) U.S. president John Kennedy announced the goal of landing Americans on the Moon by the end of the decade. Kennedy's ambitious speech triggered a nearly unprecedented peacetime technological mobilization and one result was the Saturn V moon rocket. Its development directed by rocket pioneer Wernher Von Braun, the three stage Saturn V stood over 36 stories tall. It had a cluster of five first stage engines fueled by liquid oxygen and kerosene which together were capable of producing 7.5 million pounds of thrust. Giant Saturn V rockets ultimately hurled nine Apollo missions to the Moon and back again with six landing on the lunar surface. The first landing, by Apollo 11, occurred on July 20, 1969 achieving Kennedy's goal. Bathed in light, this Saturn V awaits an April 11, 1970 launch on the third lunar landing mission, Apollo 13.",
  },
  {
    id: 17,
    name: "Hubble Floats Free",
    title: "Space Tech",
    subtitle: "Rockets and Observatories",
    type: {
      star: false,
      solarsystem: false,
      spacetech: true,
    },
    image: "/assets/images/hst_sts82_big-600h.jpg",
    credit: "STS-82 Crew, STScI, NASA",
    date: "2002 November 24",
    featured: false,
    explanation:
      "Why put observatories in space? Most telescopes are on the ground. On the ground, you can deploy a heavier telescope and fix it more easily. The trouble is that Earth-bound telescopes must look through the Earth's atmosphere. First, the Earth's atmosphere blocks out a broad range of the electromagnetic spectrum, allowing a narrow band of visible light to reach the surface. Telescopes which explore the Universe using light beyond the visible spectrum, such as those onboard the Chandra X-ray Observatory need to be carried above the absorbing atmosphere. Second, the Earth's atmosphere blurs the light it lets through. The blurring is caused by varying density and continual motion of air. By orbiting above the Earth's atmosphere, the Hubble Space Telescope, pictured above, can get clearer images. In fact, even though HST has a mirror 15 times smaller than large Earth-bound telescopes, it can still resolve finer details. A future large optical telescope in space is planned.",
  },
  {
    id: 18,
    name: "The Compton Gamma Ray Observatory",
    title: "Space Tech",
    subtitle: "Rockets and Observatories",
    type: {
      star: false,
      solarsystem: false,
      spacetech: true,
    },
    image: "/assets/images/compton_deploy_big-600h.jpg",
    credit: "STS-37 Crew, Compton Science Support Center, NASA",
    date: "2000 January 16",
    featured: false,
    explanation:
      "The Compton Gamma Ray Observatory (CGRO) was the most massive instrument ever launched by a NASA Space Shuttle in 1991 and continues to revolutionize gamma-ray astronomy. Before Compton loses more stabilizing gyroscopes, NASA is considering firing onboard rockets to bring it on a controlled reentry into the ocean. This orbiting observatory sees the sky in gamma-ray photons - light so blue humans can't see it. These photons are blocked by the Earth's atmosphere from reaching the Earth's surface. Results from CGRO, pictured above, have shown the entire universe to be a violent and rapidly changing place - when viewed in gamma-rays. Astronomers using CGRO data continue to make monumental discoveries, including identifying mysterious gamma-ray bursts that uniquely illuminate the early universe, discovery of a whole new class of QSOs, and discovery of objects so strange that astronomers can't yet figure out what they are.",
  },
  {
    id: 19,
    name: "The International Space Station from Above",
    title: "Space Tech",
    subtitle: "Rockets and Observatories",
    type: {
      star: false,
      solarsystem: false,
      spacetech: true,
    },
    image: "/assets/images/iss2_sts114_big-600h.jpg",
    credit: "STS-114 Crew, NASA",
    date: "2006 May 16",
    featured: false,
    explanation:
      "The International Space Station (ISS) is the largest human-made object ever to orbit the Earth. Last August, the station was visited and resupplied by space shuttle Discovery. The ISS is currently operated by the Expedition 13 crew, consisting a Russian and an American astronaut. After departing the ISS, the crew of Discovery captured this spectacular vista of the orbiting space city high above the Caspian Sea. Visible components include modules, trusses, and expansive solar arrays that gather sunlight that is turned into needed electricity.",
  },
  {
    id: 20,
    name: "The Space Shuttle Docked with Mir",
    title: "Space Tech",
    subtitle: "Rockets and Observatories",
    type: {
      star: false,
      solarsystem: false,
      spacetech: true,
    },
    image: "/assets/images/shuttlemir_nasa_big-600h.jpg",
    credit: "Nikolai Budarin, Russian Space Research Institute, NASA",
    date: "2002 October 20",
    featured: false,
    explanation:
      "Before there was the International Space Station, the reigning orbiting spaceport was Russia's Mir. Pictured above in 1995, the United States Space Shuttle Atlantis docked with the segmented Mir. During shuttle mission STS-71, astronauts answered questions from school students over amateur radio and performed science experiments aboard Spacelab. The Spacelab experiments helped to increase understanding of the effects of long-duration space flights on the human body. Last year, after 15 years of successful service, the decaying Mir space station broke up as it entered the Earth's atmosphere.",
  },
  {
    id: 21,
    name: "Skylab Over Earth",
    title: "Space Tech",
    subtitle: "Rockets and Observatories",
    type: {
      star: false,
      solarsystem: false,
      spacetech: true,
    },
    image: "/assets/images/skylab_nasa_big-600h.jpg",
    credit: "Skylab, NASA",
    date: "2006 April 29",
    featured: false,
    explanation:
      "Skylab was an orbiting laboratory launched by a Saturn V rocket in May 1973. Skylab, pictured above, was visited three times by NASA astronauts who sometimes stayed as long as two and a half months. Many scientific tests were performed on Skylab, including astronomical observations in ultraviolet and X-ray light. Some of these observations yielded valuable information about Comet Kohoutek, our Sun and about the mysterious X-ray background - radiation that comes from all over the sky. Skylab fell back to earth on 11 July 1979.",
  },
];
